n=input("enetr a name:")
print("Hello",n,sep=",",end="!")

z=int(input("enetr a number:"))
print("You entered:",z,sep="")
a=float(input("enetr a float value:"))
print("Value of Pi:",a,sep="")
b=input()
x,y,z=b.split(" ")
sum=int(x)+int(y)+int(z)
print("Sum of Inputs:",sum,sep="")
x=input("enetr name and age:")
name,age=x.split(",")
print("Name:",name,"Age:",age,sep="")
c=int(input("enetr a number:"))
print("Countdown:5 4 3 2 1",end="Blast Off!")
a,b=input("enetr a and b values:").split(",")
h=int(a)
i=int(b)
print("addition:",h+i,",subtraction:",h-i,",multiplication:",h*i,",division:",h/i,sep="")
